# 1. Create a 3x3x3 array with random values 

In [10]:
import numpy as np
import random
data = np.random.random((3,3,3))
data

array([[[0.9677749 , 0.59852035, 0.91429104],
        [0.39997633, 0.29718231, 0.52743332],
        [0.4981364 , 0.18210915, 0.44071317]],

       [[0.26081154, 0.14758157, 0.45142239],
        [0.96740581, 0.99734651, 0.25985732],
        [0.58828846, 0.30281249, 0.71706587]],

       [[0.99712711, 0.33717504, 0.67852738],
        [0.58818244, 0.02833709, 0.03767422],
        [0.31682084, 0.35146322, 0.38630333]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
d= np.zeros((8,8),dtype="int")
d[1::2,::2] = 1           
d[::2,1::2] = 1           
print(d)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [25]:
D = np.random.random((5,5))
D = (D- np.mean(D))/(np.std(D))
D

array([[ 0.41408473,  0.69801013,  1.11349388,  0.03581008, -1.57269215],
       [ 0.21784827,  0.45820177,  0.52927634, -0.96890762, -1.39742319],
       [-0.70274754,  1.35771313, -0.09887545,  0.42944978,  1.15987253],
       [-1.1061929 , -1.21440853, -0.57336098, -1.39836068,  1.02811454],
       [ 1.32975584, -1.36817765,  1.17668349, -0.81138077,  1.26421295]])

# 5.  How to find common values between two arrays?

In [30]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
a = np.intersect1d(a1,a2)
a

array([0, 3, 8])

# 6.How to get the dates of yesterday, today and tomorrow?

In [36]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-31
2020-08-01
2020-08-02


# 7. Consider two random array A and B, check if they are equal

In [39]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(np.allclose(a,b))         #Check with tolerance
print(np.array_equal(a,b))      #Check without tolerance

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [40]:
z= np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.82112003 0.87268504 0.66517506 0.         0.38106705 0.10699138
 0.01229235 0.94758647 0.81561935 0.68345399]


# 9. How to print all the values of an array?

In [41]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [45]:
a = np.random.rand(4,8)
b = a - a.mean(axis = 1,keepdims =True)
b

array([[ 0.39784491,  0.04133844,  0.21812389,  0.09650593, -0.34327885,
        -0.41269902,  0.08816597, -0.08600127],
       [ 0.39430271,  0.43823565, -0.52378415, -0.06225211, -0.46108774,
         0.12744249, -0.0229307 ,  0.11007386],
       [-0.12070961, -0.02013358, -0.15170721, -0.40341808,  0.41668259,
         0.14110518, -0.25552138,  0.39370209],
       [ 0.29310792, -0.01152337, -0.04507052,  0.37763904,  0.06489911,
        -0.088225  , -0.49338834, -0.09743884]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [47]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[2. 7. 2. 2. 5. 3. 2. 2. 2. 3.]
[ 3. 13.  3.  3.  9.  5.  3.  3.  3.  5.]


# 12.How to get the diagonal of a dot product?

In [48]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
p=np.diag(np.dot(A, B))
p

[[0.75895674 0.98099204 0.30184727 0.85228975 0.20004891]
 [0.96301073 0.25678004 0.93881045 0.90155012 0.64900645]
 [0.7773376  0.64459668 0.04895268 0.36880127 0.38241818]
 [0.14020184 0.29767292 0.8612159  0.47993831 0.91952565]
 [0.22591306 0.81340613 0.65423218 0.00101658 0.58156435]]
[[0.92499233 0.13067778 0.27862891 0.31931299 0.15135954]
 [0.51977549 0.75034932 0.92856885 0.35473418 0.18174304]
 [0.55275238 0.19176817 0.66399936 0.0502064  0.9372128 ]
 [0.09946079 0.97374707 0.3884861  0.06033474 0.85270902]
 [0.25223505 0.7491268  0.6704539  0.64610118 0.1496887 ]]


array([1.51400034, 1.86262271, 1.24731359, 0.81666514, 0.88310023])

# 13.How to find the most frequent value in an array?

In [49]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[0 5 0 8 9 1 1 0 6 0 5 6 3 3 1 7 4 4 5 2 7 9 6 4 8 2 6 3 2 5 9 6 3 8 7 7 5
 4 9 9 9 5 4 1 3 1 4 8 0 8]
4


# 14.How to get the n largest values of an array

In [51]:
s = np.arange(2000)
np.random.shuffle(s)
n = 5
print (s[np.argsort(s)[-n:]])

[1995 1996 1997 1998 1999]


# 15.How to create a record array from a regular array?

In [57]:
Z = np.array([("Hello", 5.0, 4),
              ("AI", 9.8, 7)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 5. , 4) (b'AI', 9.8, 7)]
